# .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    name: Build & Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Build React App
        run: npm run build

  docker-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nibrasdocker/sm-app:${{ github.run_id }}

  update-helm-tag:
    name: Update Helm Chart Image Tag
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update image tag in Helm values.yaml
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" helm/sm-app-chart/values.yaml

      - name: Commit and Push changes
        run: |
          git config --global user.name "Nibras-S"
          git config --global user.email "connectnibras@gmail.com"
          git add helm/sm-app-chart/values.yaml
          git commit -m "Update image tag to ${{ github.run_id }}"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
